#!/bin/bash

# This test confirms that the sample_test_static.h is kept up to date.
# This primarily serves to allow people to easily see what changes to
# generated code will looks like when doing code reviews. The checked-in
# file can be regenerated by running
# $ bazel run @org_frc971//aos/flatbuffers/test_dir:copy_test_static_header
diff $1 $2
