#!/bin/bash --norc

LD_LIBRARY_PATH="${BAZEL_OUTPUT_ROOT}external/clang_6p0_repo/usr/lib/x86_64-linux-gnu"
LD_LIBRARY_PATH+=":${BAZEL_OUTPUT_ROOT}external/clang_6p0_repo/usr/lib"
export LD_LIBRARY_PATH

PATH="${BAZEL_OUTPUT_ROOT}external/clang_6p0_repo/usr/lib/gcc/x86_64-linux-gnu/4.9:$PATH" \
  exec \
  ${BAZEL_OUTPUT_ROOT}external/clang_6p0_repo/usr/bin/gcc \
  "$@"
