cc_binary(
  name = "image_streamer",
  srcs = ["image_streamer.cc"],
  deps = [
    "//aos/vision/events:socket_types",
    '//aos/vision/events:epoll_events',
    '//aos/vision/image:reader',
    '//aos/vision/image:image_stream',
    '//aos/vision/blob:codec',
    '//aos/common/logging:logging',
    '//aos/common/logging:implementations',
  ],
)
