package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'driver_station_data',
  srcs = [
    'driver_station_data.cc',
  ],
  hdrs = [
    'driver_station_data.h',
  ],
  deps = [
    '//aos/common/messages:robot_state',
  ],
)
