// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "FrisbeeStorage.h"
#include "../Robotmap.h"
FrisbeeStorage::FrisbeeStorage() : Subsystem("FrisbeeStorage") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	frisbeeIndexerMotor = RobotMap::frisbeeStorageFrisbeeIndexerMotor;
	frisbeeIndexerSpeedEncoder = RobotMap::frisbeeStorageFrisbeeIndexerSpeedEncoder;
	frisbeeInputOpticalSensor = RobotMap::frisbeeStorageFrisbeeInputOpticalSensor;
	frisbeeIndexOpticalSensor = RobotMap::frisbeeStorageFrisbeeIndexOpticalSensor;
	frisbeeReadytoshootOpticalSensor = RobotMap::frisbeeStorageFrisbeeReadytoshootOpticalSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void FrisbeeStorage::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
