package(default_visibility = ['//y2015:__subpackages__'])

py_binary(
  name = 'arm',
  srcs = [
    'arm.py',
  ],
  deps = [
    '//external:python-gflags',
    '//external:python-glog',
    '//frc971/control_loops/python:controls',
  ],
)

py_binary(
  name = 'claw',
  srcs = [
    'claw.py',
  ],
  deps = [
    '//external:python-gflags',
    '//external:python-glog',
    '//frc971/control_loops/python:controls',
  ],
)
