package(default_visibility = ["//y2024_bot3:__subpackages__"])

py_library(
    name = "python_init",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
    deps = ["//y2024_bot3/control_loops:python_init"],
)
