package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'position_sensor_sim',
  srcs = [
    'position_sensor_sim.cc',
  ],
  hdrs = [
    'position_sensor_sim.h',
  ],
  deps = [
    '//bot3/control_loops/elevator:elevator_queue',
  ],
)
