package(default_visibility = ['//visibility:public'])

load('/aos/build/queues', 'queue_library')

queue_library(
  name = 'ball_detector',
  srcs = [
    'ball_detector.q',
  ],
)

queue_library(
  name = 'profile_params',
  srcs = [
    'profile_params.q',
  ],
)
