# This file is run by shell scripts generated by the aos_downloader Skylark
# macro. Everything before the first -- is a hard-coded list of files to
# download.

import sys
import subprocess

def main(argv):
  srcs = argv[:argv.index('--')]
  args = argv[argv.index('--') + 1:]

  # TODO(Brian): Actually do something useful...
  subprocess.check_call(['echo', 'scp'] + srcs + ['%s:/tmp' % args[0]])

if __name__ == '__main__':
  main(sys.argv)
