filegroup(
  name = 'prime_binaries',
  visibility = ['//visibility:public'],
  srcs = [
    '//aos/linux_code:core',
    '//aos/linux_code/logging:log_streamer',
    '//aos/linux_code/logging:log_displayer',
    '//aos/linux_code/starter',
  ],
)
filegroup(
  name = 'prime_start_binaries',
  visibility = ['//visibility:public'],
  srcs = [
    '//aos/linux_code/logging:binary_log_writer',
  ],
)
