package(default_visibility = ['//visibility:public'])

filegroup(
  name = 'All',
  srcs = [
    '//aos:prime_binaries',
    '//y2015/control_loops/drivetrain:drivetrain',
    '//y2015/control_loops/drivetrain:drivetrain_lib_test',
    '//y2015/control_loops/drivetrain:replay_drivetrain',
    '//y2015/control_loops/fridge:fridge',
    '//y2015/control_loops/fridge:fridge_lib_test',
    '//y2015/control_loops/fridge:replay_fridge',
    '//y2015/control_loops/claw:claw',
    '//y2015/control_loops/claw:claw_lib_test',
    '//y2015/control_loops/claw:replay_claw',
    '//y2015/autonomous:auto',
    '//y2015:joystick_reader',
    '//y2015/http_status:http_status',
    '//y2015/util:kinematics_test',
    '//y2015/actors:binaries',
  ],
)
