sh_binary(
    name = "quiet_success",
    srcs = ["quiet_success.sh"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "jinja2_generator",
    srcs = ["jinja2_generator.py"],
    visibility = ["//visibility:public"],
    deps = ["@python_jinja2"],
)
