package(default_visibility = ['//y2014_bot3:__subpackages__'])

py_binary(
  name = 'drivetrain',
  srcs = [
    'drivetrain.py',
  ],
  deps = [
    '//external:python-glog',
    '//frc971/control_loops/python:controls',
  ]
)
