package(default_visibility = ["//visibility:public"])

load("@com_github_google_flatbuffers//:build_defs.bzl", "flatbuffer_cc_library")

flatbuffer_cc_library(
    name = "ball_detector_fbs",
    srcs = [
        "ball_detector.fbs",
    ],
    gen_reflections = 1,
)
