package(default_visibility = ['//visibility:public'])

load('/aos/build/queues', 'queue_library')

queue_library(
  name = 'profile_params',
  srcs = [
    'profile_params.q',
  ],
)

queue_library(
  name = 'hot_goal',
  srcs = [
    'hot_goal.q',
  ],
)

queue_library(
  name = 'auto_mode',
  srcs = [
    'auto_mode.q',
  ],
)
