package(default_visibility = ['//visibility:public'])

# Don't use these directly! Use //tools/build_rules/select.bzl instead.
config_setting(
  name = 'compiler_clang',
  values = {'compiler': 'clang'}
)
config_setting(
  name = 'compiler_gcc',
  values = {'compiler': 'gcc'}
)
config_setting(
  name = 'cpu_k8',
  values = {'cpu': 'k8'},
)
config_setting(
  name = 'cpu_roborio',
  values = {'cpu': 'roborio'},
)
