package(default_visibility = ["//visibility:public"])

cc_library(
    name = "scoped_fd",
    hdrs = [
        "scoped_fd.h",
    ],
    compatible_with = [
        "//tools:armhf-debian",
    ],
    deps = [
        "//aos/logging",
    ],
)
